### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by geforcexfx** [TOTON95/Bebop_ROS_Examples#5]
Hello. I am very new to ROS. I have already connected my parrot bebop2 and it can take of by : $ roslaunch bebop_driver bebop_node.launch . Can you tell me after I clone this package, do I need to do anything else? How can I run bebop_simple_test? thanks

**Comment by TOTON95** [comment]
Hello! Welcome aboard! 
Before flying your drone, I suggest you look into some ROS tutorials that are available on the internet. Then just allocate it in a valid catkin workspace and run `catkin_make`.
