### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by GeneralAdmin** [TOTON95/Bebop_ROS_Examples#6]
could not find

#include <Bebop_waypoints/Waypoints.h>

can you please take a look?

**Comment by TOTON95** [comment]
@GeneralAdmin Have you generated the messages? Try to compile it again, this file needs to be generated from ROS automatically.  It will be located in your `devel/include` folder, no actions are required after that.

**Comment by GeneralAdmin** [comment]
Hi! 
  for some reason is not being generated in my machine. I've tried again, I'm using catkin build in ubuntu 16 with ROS kinectic. 

To solve I deleted this part of the package and was able to compile the other ones!

Thank you very much!!!!
