### ISSUE TITLE
Missing files 

### ISSUE THREAD

**Issue by GeneralAdmin** [TOTON95/Bebop_ROS_Examples#7]
There are two missing files in the waypoint node:

#include <Bebop_waypoints/Waypoints.h>
#include <Bebop_waypoints/Waypoint.h>

**Comment by TOTON95** [comment]
@GeneralAdmin Hi there! They should be generated once you call `catkin_make`, try to run it twice.

**Comment by GeneralAdmin** [comment]
> @GeneralAdmin Hi there! They should be generated once you call `catkin_make`, try to run it twice.

It makes sense, i was using catkin build and that could be the issue then. I will try it tomorow morning.
